[package]
name = "openim-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi" }
tools = { path = "../tools" }
entity = { path = "../entity" }

tracing = { workspace = true }
serde = { workspace = true }
bson = { workspace = true }
