connect_timeout: 5000
timeout: 3000
brokers:
  - 192.168.0.230:9092
producer:
  timeout: 3000
  acks: all # 0: no response, 1: leader response, all: all response
  max_retry: 3
  retry_interval: 1000 # retry interval in milliseconds
consumer:
  auto_offset_reset: earliest # earliest, latest
  session_timeout: 20000
