secret: openIM123
im_admin_user_id: [ imAdmin ]

# 1: For Android, iOS, Windows, Mac, and web platforms, only one instance can be online at a time
multiLogin:
  policy: 1
  # max num of tokens in one end
  max_num_one_end: 30