[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi" }

thiserror = { workspace = true }
tracing = { workspace = true }

# nacos
nacos_rust_client = { workspace = true  }
nacos-tonic-discover = { workspace = true }