[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
abi = { path = "../abi" }
openim-storage = { path = "../storage" }
tools = { path = "../tools" }

serde = { workspace = true }
tracing = { workspace = true, features = ["log"]}
